version: '3'
services:
        exporter:
                image: nginx/nginx-prometheus-exporter:0.4.2
                environment:
                  #- SCRAPE_URI=http://18.219.219.70:8080/metrics
                  - SCRAPE_URI=http://localhost:8080/metrics
                  - TELEMETRY_PATH=/prometheus
                  - NGINX_RETRIES=10
                ports: 
                  - "9113:9113"
                networks:
                        redinha:
                                aliases:
                                  - prometheus_exporter

networks:
  redinha:
