version: '3.7'
services:
        c_web:
                image: nginx_vitor:latest
                ports:
                  - "8080:80"
                networks:
                        redinha:
                                aliases:
                                  - nginx_container
        prometheus:
                image: prom/prometheus
                ports:
                  - "9090:9090"
                volumes:
                  - ./prometheus.yml:/etc/prometheus/prometheus.yml
                networks:
                        redinha:
                                aliases:
                                  - prometheus_container
                #links:
                  #- exporter
        grafana:
                image: grafana/grafana
                ports:
                  - "3000:3000"
                networks:
                        redinha:
                                aliases:
                                  - grafana_container
                links:
                  - prometheus

networks:
  redinha:
