version: '3'
services:
        web:
                image: nginx_vitor:latest
                ports:
                  - "8080:80"
        exporter:
                image: nginx/nginx-prometheus-exporter:0.4.2
                environment:
                  - SCRAPE_URI=http://host.docker.internal:8080/metrics
                  - TELEMETRY_PATH=/prometheus
                  - NGINX_RETRIES=10
                ports: 
                  - "9113:9113"
                links:
                  - web
                depends_on:
                  - web
        prometheus:
                image: prom/prometheus
                ports:
                  - "9090:9090"
                volumes:
                  - ./prometheus.yml:/etc/prometheus/prometheus.yml
                links:
                  - exporter
                depends_on:
                  - exporter
        grafana:
                image: grafana/grafana
                ports:
                  - "3000:3000"
                links:
                  - prometheus

